# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsum',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
